/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage;

import ASM.Login;
import Model.Billsell;
import Model.CoffeeSR;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import lib.Xfile;

/**
 *
 * @author SON RATTANA
 */
public class SRCoffee extends javax.swing.JFrame {

    DefaultTableModel tbModel;
    DefaultTableModel tblModel;
    DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
    DefaultComboBoxModel cblistModel = new DefaultComboBoxModel();
    String filePath = "";
    ArrayList<CoffeeSR> coffeeList;
    String fileBill = "";
    ArrayList<Billsell> coffeeBill;
    int currentRow = -1;
    CardLayout cardLayout;
    Map<String, String> menu;

    /**
     * Creates new form SRBus
     */
    public SRCoffee() {
        initComponents();
        initTable();
        tblCoffeeMenu.setDefaultEditor(Object.class, null);
        tblBill.setDefaultEditor(Object.class, null);
        loadCb();
        loadCb2();
        btnadd.setEnabled(true);
        btndelete.setEnabled(false);
        tblCoffee.setDefaultEditor(Object.class, null);
        filePath = "./src/lib/coffesr.dat";
        coffeeList = new ArrayList<>();
        boolean file = loadFile();

        if (file) {
            fillToTable();
        } else {
            showMess("Nothing to Show");
        }
        fileBill = "./src/lib/Bill.dat";
        coffeeBill = new ArrayList<>();
        boolean fileB = loadFileBill();
        if (fileB) {
            fillToTableBill();
        }
        this.setTitle("Coffee");
        this.setLocationRelativeTo(null);
        cardLayout = (CardLayout) contentpanel.getLayout();
        menu = new HashMap<>();
    }

    private void fillToTable() {
        tbModel.setRowCount(0);
        for (CoffeeSR c : coffeeList) {
            Object[] row = new Object[]{c.getCode(), c.getName(), c.getPrice(), c.getCategory()};
            tbModel.addRow(row);
        }
    }

    private void fillToTableBill() {
        for (Billsell b : coffeeBill) {
            Object[] rowBill = new Object[]{b.getCode(), b.getName(), b.getPrice(), b.getCategory(), b.getDate()};
            tblModel.addRow(rowBill);
        }
    }

    private boolean loadFile() {
        if (Xfile.readObject(filePath) == null) {
            return false;
        }
        coffeeList = (ArrayList<CoffeeSR>) Xfile.readObject(filePath);
        return true;
    }

    private boolean loadFileBill() {
        if (Xfile.readObject(fileBill) == null) {
            return false;
        }
        coffeeBill = (ArrayList<Billsell>) Xfile.readObject(fileBill);
        return true;
    }

    private void showMess(String mess) {
        JOptionPane.showMessageDialog(this, mess);
    }

    private void loadCb() {
        String[] cateLst = {"Coffee", "Milk-tea", "Tea"};
        for (String string : cateLst) {
            cbModel.addElement(string);
        }
        cbcate.setModel(cbModel);

    }

    private void loadCb2() {
        String[] filteLst = {"None", "Coffee", "Milk-tea", "Tea"};
        for (String filter : filteLst) {
            cblistModel.addElement(filter);
        }
        cblist.setModel(cblistModel);
    }

    private void initTable() {
        String[] columnNames = {"Code", "Name", "Price", "Category"};
        tbModel = new DefaultTableModel(columnNames, 0);
        tblCoffee.setModel(tbModel);
        tblCoffeeMenu.setModel(tbModel);

        String[] coloumBills = {"Code", "Name", "Price", "Category", "Date"};
        tblModel = new DefaultTableModel(coloumBills, 0);
        tblBill.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbCoffee = new javax.swing.JLabel();
        lbSell = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        lbexit = new javax.swing.JLabel();
        lbexit1 = new javax.swing.JLabel();
        contentpanel = new javax.swing.JPanel();
        coffee = new javax.swing.JPanel();
        lbManagement = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        cbcate = new javax.swing.JComboBox<>();
        lbcode = new javax.swing.JLabel();
        lbprice = new javax.swing.JLabel();
        lbcate = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoffee = new javax.swing.JTable();
        cblist = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        sell = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtprice2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnbill = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtnamesell = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCoffeeMenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 33, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/z4275027148088_7d717dced5e146f4942e577faa94924e-removebg-preview.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(126, 126));
        jLabel3.setMinimumSize(new java.awt.Dimension(126, 126));
        jPanel4.add(jLabel3);

        lbCoffee.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbCoffee.setForeground(new java.awt.Color(255, 255, 255));
        lbCoffee.setText("Coffee");
        lbCoffee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCoffeeMousePressed(evt);
            }
        });
        jPanel4.add(lbCoffee);

        lbSell.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbSell.setForeground(new java.awt.Color(255, 255, 255));
        lbSell.setText("Sell Items");
        lbSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbSellMousePressed(evt);
            }
        });
        jPanel4.add(lbSell);

        lbLogout.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setText("Logout");
        lbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });
        jPanel4.add(lbLogout);

        lbexit.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbexit.setForeground(new java.awt.Color(255, 255, 255));
        lbexit.setText("Exit");
        lbexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbexitMousePressed(evt);
            }
        });
        jPanel4.add(lbexit);

        lbexit1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbexit1.setForeground(new java.awt.Color(255, 255, 255));
        lbexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_tea_cup_100px.png"))); // NOI18N
        lbexit1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbexit1MousePressed(evt);
            }
        });
        jPanel4.add(lbexit1);

        contentpanel.setLayout(new java.awt.CardLayout());

        lbManagement.setBackground(new java.awt.Color(255, 255, 255));
        lbManagement.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbManagement.setText("Coffee Management");

        txtcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcodeFocusGained(evt);
            }
        });

        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });

        txtprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpriceFocusGained(evt);
            }
        });

        cbcate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcateActionPerformed(evt);
            }
        });

        lbcode.setText("Code");

        lbprice.setText("Price");

        lbcate.setText("Category");

        lbname.setText("Name");

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.setToolTipText("");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tblCoffee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Category"
            }
        ));
        tblCoffee.setShowHorizontalLines(true);
        tblCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCoffeeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCoffee);

        cblist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cblistItemStateChanged(evt);
            }
        });
        cblist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cblistMousePressed(evt);
            }
        });

        jLabel2.setText("Filter");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("List");

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coffeeLayout = new javax.swing.GroupLayout(coffee);
        coffee.setLayout(coffeeLayout);
        coffeeLayout.setHorizontalGroup(
            coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeeLayout.createSequentialGroup()
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coffeeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(coffeeLayout.createSequentialGroup()
                                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(coffeeLayout.createSequentialGroup()
                                        .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbcode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbprice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbname, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coffeeLayout.createSequentialGroup()
                                        .addComponent(lbcate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname)
                                    .addComponent(txtprice)
                                    .addComponent(cbcate, 0, 203, Short.MAX_VALUE))
                                .addGap(52, 52, 52))
                            .addGroup(coffeeLayout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnreset)
                                .addGap(12, 12, 12))
                            .addGroup(coffeeLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cblist, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coffeeLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
            .addGroup(coffeeLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(lbManagement)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coffeeLayout.setVerticalGroup(
            coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeeLayout.createSequentialGroup()
                .addComponent(lbManagement)
                .addGap(24, 24, 24)
                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coffeeLayout.createSequentialGroup()
                        .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coffeeLayout.createSequentialGroup()
                                .addComponent(lbcode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbprice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbcate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnedit)
                            .addComponent(btndelete)
                            .addComponent(btnreset))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addGroup(coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cblist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        contentpanel.add(coffee, "coffee");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Selling");

        txtprice2.setEditable(false);
        txtprice2.setEnabled(false);

        jLabel6.setText("Price");

        jLabel7.setText("Name");

        btnbill.setText("Add to Bill");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Date"
            }
        ));
        tblBill.setShowHorizontalLines(true);
        jScrollPane3.setViewportView(tblBill);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("Bill");

        txtnamesell.setEnabled(false);

        tblCoffeeMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Category"
            }
        ));
        tblCoffeeMenu.setShowHorizontalLines(true);
        tblCoffeeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCoffeeMenuMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblCoffeeMenu);

        javax.swing.GroupLayout sellLayout = new javax.swing.GroupLayout(sell);
        sell.setLayout(sellLayout);
        sellLayout.setHorizontalGroup(
            sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellLayout.createSequentialGroup()
                .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellLayout.createSequentialGroup()
                        .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sellLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtprice2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtnamesell))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnbill)
                                .addGap(108, 108, 108)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sellLayout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabel9))
                    .addGroup(sellLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(382, 382, 382))
        );
        sellLayout.setVerticalGroup(
            sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellLayout.createSequentialGroup()
                .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamesell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnbill))
                    .addGroup(sellLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        contentpanel.add(sell, "sell");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if (Check() == true) {
            addCan();
            fillToTable();
            saveFile();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private boolean Check() {
        String code = txtcode.getText();
        if (!"".equals(txtcode.getText()) && !"".equals(txtname.getText())) {

            for (CoffeeSR cf : coffeeList) {
                CoffeeSR coffee = new CoffeeSR(cf.getCode(), cf.getName(), cf.getPrice());
                if (code.equals(cf.getCode())) {
                    txtcode.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Code is available!");
                    return false;
                }
            }
            String Price = txtprice.getText();
            for (int i = 0; i < Price.length(); i++) {
                Boolean flags = Character.isDigit(Price.charAt(i));
                if (!flags) {
                    txtprice.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Price must be number");
                    return false;
                }
            }
            String name = txtname.getText();
            if (name.equals(name)) {
                setBackground(Color.white);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Plase enter all infor");
            txtcode.setBackground(Color.red);
            txtname.setBackground(Color.red);
            txtprice.setBackground(Color.red);
            return false;
        }

        txtcode.setBackground(Color.white);
        txtname.setBackground(Color.white);
        txtprice.setBackground(Color.white);
        return true;
    }

    private void cbcateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcateActionPerformed
        // TODO add your handling code here:
        String f = cbcate.getSelectedItem().toString();
        for (Map.Entry<String, String> entry : menu.entrySet()) {
            if (entry.getValue().equals(f)) {
                txtcode.setText(entry.getKey());
                break;
            }
        }
    }//GEN-LAST:event_cbcateActionPerformed

    private void lbCoffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCoffeeMousePressed
        // TODO add your handling code here:
        cardLayout.show(contentpanel, "coffee");

    }//GEN-LAST:event_lbCoffeeMousePressed

    private void lbSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMousePressed
        // TODO add your handling code here:
        cardLayout.show(contentpanel, "sell");

    }//GEN-LAST:event_lbSellMousePressed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        deleteCan();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btndeleteActionPerformed


    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Do you wanna Logout?", "Logout?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lbLogoutMousePressed

    private void lbexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Do you wanna exit?", "Exit?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "You Are Still In The App");
        }
    }//GEN-LAST:event_lbexitMousePressed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        btnadd.setEnabled(false);
        resetForm();
        txtcode.setBackground(Color.white);
        txtname.setBackground(Color.white);
        txtprice.setBackground(Color.white);

    }//GEN-LAST:event_btnresetActionPerformed

    private void tblCoffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoffeeMousePressed
        // TODO add your handling code here:
        btnadd.setEnabled(false);
        btndelete.setEnabled(true);
        currentRow = tblCoffee.getSelectedRow();
        showDetail(currentRow);
    }//GEN-LAST:event_tblCoffeeMousePressed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if (Checkedit() == true) {
            editCan();
            fillToTable();
            saveFile();
        }
    }//GEN-LAST:event_btneditActionPerformed
    private boolean Checkedit() {

        if (!"".equals(txtcode.getText()) && !"".equals(txtname.getText())) {

            String Price = txtprice.getText();
            for (int i = 0; i < Price.length(); i++) {
                Boolean flags = Character.isDigit(Price.charAt(i));
                if (!flags) {
                    txtprice.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Price must be number");
                    return false;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Plase enter all infor");
            txtcode.setBackground(Color.red);
            txtname.setBackground(Color.red);
            txtprice.setBackground(Color.red);
            return false;
        }

        txtcode.setBackground(Color.white);
        txtname.setBackground(Color.white);
        txtprice.setBackground(Color.white);
        return true;
    }

    private void resetForm() {
        btnadd.setEnabled(true);
        txtcode.setText("");
        txtname.setText("");
        txtprice.setText("");
        cbcate.setSelectedIndex(0);
    }

    private void addCan() {
        if (txtcode.getText().isEmpty() || txtname.getText().isEmpty() || txtprice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all infor of product");
        } else {
            String code = txtcode.getText();
            String name = txtname.getText().trim();
            Integer price = Integer.parseInt(txtprice.getText());
            String category = cbcate.getSelectedItem().toString();
            CoffeeSR c = new CoffeeSR(code, name, price, category);
            if (price <= 0) {
                showMess("You must enter price than 0");
            } else {
                coffeeList.add(c);
            }

        }
    }

    private void deleteCan() {
        String code = txtcode.getText();
        int result = JOptionPane.showConfirmDialog(this, "Do you wanna to delete?", "Delete?",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            coffeeList.remove(currentRow);
        }

    }

    private void editCan() {
        if (txtcode.getText().isEmpty() || txtname.getText().isEmpty() || txtprice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plase Choose row ");
        } else {
            CoffeeSR c = coffeeList.get(currentRow);
            c.setName(txtname.getText().trim());
            c.setPrice(Integer.parseInt(txtprice.getText()));
            c.setCategory(cbcate.getSelectedItem().toString());
        }
    }

    private void cblistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cblistMousePressed
        // TODO add your handling code here:
        if (Xfile.readObject(filePath) == null) {

        }
        coffeeList = (ArrayList<CoffeeSR>) Xfile.readObject(filePath);
        cblist.getSelectedItem().toString();

    }//GEN-LAST:event_cblistMousePressed

    private void cblistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cblistItemStateChanged
        // TODO add your handling code here:
        String kw = cblist.getSelectedItem().toString();
        filter(kw);
    }//GEN-LAST:event_cblistItemStateChanged

    private void tblCoffeeMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoffeeMenuMousePressed
        // TODO add your handling code here:

        currentRow = tblCoffeeMenu.getSelectedRow();
        showDetailMenusell(currentRow);
    }//GEN-LAST:event_tblCoffeeMenuMousePressed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:

        addBill();
        fillToTableBill();
        saveFileBill();
    }//GEN-LAST:event_btnbillActionPerformed

    private void txtcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodeFocusGained
        // TODO add your handling code here:
        txtcode.setBackground(Color.white);
    }//GEN-LAST:event_txtcodeFocusGained

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        txtname.setBackground(Color.white);
    }//GEN-LAST:event_txtnameFocusGained

    private void txtpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusGained
        // TODO add your handling code here:
        txtprice.setBackground(Color.white);
    }//GEN-LAST:event_txtpriceFocusGained

    private void lbexit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbexit1MousePressed

    private void addBill() {
        if (txtcode.getText().isEmpty() || txtnamesell.getText().isEmpty() || txtprice2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plase Choose row ");
        } else {
            String code = txtcode.getText();
            String name = txtnamesell.getText();
            Integer price = Integer.parseInt(txtprice2.getText());
            String category = cbcate.getSelectedItem().toString();
            Date date = new Date();

            Billsell b = new Billsell(code, name, price, category, date);
            coffeeBill.add(b);
        }

    }

    private void filter(String kw) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tbModel);
        tblCoffee.setRowSorter(tr);

        if (!"None".equals(kw)) {
            tr.setRowFilter(RowFilter.regexFilter(kw, 3));
        } else {
            tblCoffee.setRowSorter(tr);
        }
    }

    private void showDetail(int r) {
        String code = (String) tblCoffee.getValueAt(r, 0);
        txtcode.setText(code);
        String name = (String) tblCoffee.getValueAt(r, 1);
        txtname.setText(name);

        Integer price = (Integer) tblCoffee.getValueAt(r, 2);
        txtprice.setText(price.toString());

        String cate = (String) tblCoffee.getValueAt(r, 3);
        cbcate.setSelectedItem(cate);
    }

    private void showDetailMenusell(int s) {
        String code = (String) tblCoffee.getValueAt(s, 0);
        txtcode.setText(code);
        String name = (String) tblCoffee.getValueAt(s, 1);

        txtnamesell.setText(name);
        Integer price = (Integer) tblCoffee.getValueAt(s, 2);

        txtprice2.setText(price.toString());
        String cate = (String) tblCoffee.getValueAt(s, 3);
        cbcate.setSelectedItem(cate);
    }

    private void saveFile() {
        Xfile.writeObject(filePath, coffeeList);
    }

    private void saveFileBill() {
        Xfile.writeObject(fileBill, coffeeBill);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRCoffee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRCoffee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRCoffee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRCoffee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRCoffee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbill;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> cbcate;
    private javax.swing.JComboBox<String> cblist;
    private javax.swing.JPanel coffee;
    private javax.swing.JPanel contentpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbCoffee;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbManagement;
    private javax.swing.JLabel lbSell;
    private javax.swing.JLabel lbcate;
    private javax.swing.JLabel lbcode;
    private javax.swing.JLabel lbexit;
    private javax.swing.JLabel lbexit1;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbprice;
    private javax.swing.JPanel sell;
    private javax.swing.JTable tblBill;
    private javax.swing.JTable tblCoffee;
    private javax.swing.JTable tblCoffeeMenu;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnamesell;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprice2;
    // End of variables declaration//GEN-END:variables
}
